language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install -r dependencies.txt"
  - "pip install flake8"
  - npm install -g casperjs
  # create the database
  - "cp Lagerregal/template_development.py Lagerregal/settings.py"
  - "./manage.py migrate"
# command to run tests
script:
  - flake8 --config=setup.cfg
  - "./manage.py test"
